### ISSUE TITLE
Webpacker fails compilation with Turbo import.

### ISSUE THREAD

**Issue by martinGerez** [hotwired/turbo-rails#40] opened 2020-12-26 15:31 UTC
Hi.

I'm triying to install `turbo-rails` following the README instructions. I'm using `webpacker` instead of asset-pipeline.

After install `turbo-rails` gem and add `@hotwired/turbo-rails`, when I try to import Turbo and cable in application.js, Webpacker fails compilation with following message:

```
webpacker | ERROR in ./node_modules/@hotwired/turbo-rails/app/javascript/turbo/index.js 2:9
webpacker | Module parse failed: Unexpected token (2:9)
webpacker | File was processed with these loaders:
webpacker |  * ./node_modules/babel-loader/lib/index.js
webpacker | You may need an additional loader to handle the result of these loaders.
webpacker | | import "./cable_stream_source_element";
webpacker | > export * as Turbo from "@hotwired/turbo";
webpacker | | export * as cable from "./cable";
webpacker | ℹ ｢wdm｣: Failed to compile.
```

I tried restarting the server, and re-installing dependencies.

**Comment by arpansac** [comment] 2020-12-26 16:42
Earlier installed and then removed stimulus_reflex.
Spent hours figuring out why my link_to inside a turbo frame was taking me to a different page. Finally, had to remove the javascript_pack_tag

I'm completely new to this (but quite used to rails), is this the usual behaviour? Because  webpack comes in pre-bundled with Rails!

**Comment by pjo336** [comment] 2020-12-27 02:24
So I had the same error on one project, but not another, so I was looking for the differences.

You can replicate the error in the console by running `./bin/webpack`

This also spits out the webpack version it's using. I was using a fairly old webpack version. 

I updated in my package.json to set `@rails/webpacker` to use version `5.2.1` rather than `4.0.7`, did a `yarn install` and the error is gone

**Comment by javan** [comment] 2020-12-27 02:34
Duplicate of #20

**Closed by javan** 2020-12-27 02:34 UTC
