### ISSUE TITLE
NPM Package appears to be an outdated build v1.4.0 (latest is 1.5.0) 

### ISSUE THREAD

**Issue by armstrjare** [hotwired/turbo-rails#517] opened 2023-11-22 02:53 UTC
NPM package `@hotwired/turbo-rails` Appears to be a build based on v1.4.0 here - so missing fixes made to Rails specific Form submission handling with formmethod, _method etc.  in v1.5.0

NPM Package
https://www.npmjs.com/package/@hotwired/turbo-rails

Missing these fixes from v1.5.0:
https://github.com/hotwired/turbo-rails/blob/v1.5.0/app/javascript/turbo/fetch_requests.js
https://github.com/hotwired/turbo-rails/commit/92ad1f4115e87ced02af33066eb698d7a2c21c98

I have been debugging why Turbo submissions with buttons overriding formmethod and formaction within a master form (eg. for delete buttons, etc.) were not working as expected with Turbo. I traced down that Turbo-Rails specifically adds handling for Rails' use of _method as an override. However, upon reviewing this code, it appeared as though things should still work as expected. Then I realised, that despite using the latest `turbo-rails` version, the code I have bundled appears outdated by a couple of versions, which has broken behaviour.

**Comment by armstrjare** [comment] 2023-11-22 09:42
Closing this as I appear to have gotten this wrong, apologies

**Comment by armstrjare** [comment] 2023-11-22 09:58
Apologies again, reopening, but have corrected that it is appears NPM is currently at v.1.4.0 build - so missing 1.5.0 build changes.

**Comment by brunoprietog** [comment] 2024-06-21 12:20
Hello @armstrjare, I can't reproduce this, the latest version of Turbo is correctly published in NPM. I will close it for now. Feel free to reopen it if you can provide me with more detailed steps.

**Closed by brunoprietog** 2024-06-21 12:20 UTC
