### ISSUE TITLE
Flashing flashes

### ISSUE THREAD

**Issue by ayrton** [hotwired/turbo-rails#117] opened 2021-02-09 10:23 UTC
While gradually migrating over an app to use hotwire, I've been experiencing flashing flashes when re-visiting a page (for a second time).

1. View loads 
2. Form submits
3. Page revisit (this is fine)
4. Page revisit (flashing flash)

https://user-images.githubusercontent.com/440926/107349706-d38a6d00-6ac8-11eb-8f28-6c46c9b8a22e.mov

No controller code was changed yet, this is a vanilla rails controller:

```rb
class SettingsController < ApplicationController
  def new
    @user = current_user
  end

  def create
    @user = current_user
    @user.attributes = settings_params

    if @user.save
      redirect_to user_root_path, notice: "You have successfully updated your settings"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def settings_params
    params.require(:user).permit(:email)
  end
end
```

Is this the expected behavior? Can reproduce with any controller. Do flashes need special treatment in user-land or is this something we can address through a controller concern?

__Example user land:__

```rb
class SettingsController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.attributes = settings_params

    if @user.save
      respond_to do |format|
        format.html {  redirect_to user_root_path, notice: "You have successfully updated your settings" }
        format.turbo_stream {  redirect_to user_root_path }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def settings_params
    params.require(:user).permit(:email)
  end
end
```

Happy to take stab at implementing a controller concern if that's desirable. 

Using the latest released gems/packages:

```
# Gemfile.lock 
rails (6.1.1)
  actioncable (= 6.1.1)
  actionmailbox (= 6.1.1)
  actionmailer (= 6.1.1)
  actionpack (= 6.1.1)
  actiontext (= 6.1.1)
  actionview (= 6.1.1)
  activejob (= 6.1.1)
  activemodel (= 6.1.1)
  activerecord (= 6.1.1)
  activestorage (= 6.1.1)
  activesupport (= 6.1.1)
  bundler (>= 1.15.0)
  railties (= 6.1.1)
  sprockets-rails (>= 2.0.0)
turbo-rails (0.5.9)
  rails (>= 6.0.0)
```

```
// package.json
"dependencies": {
  "@hotwired/turbo-rails": "^7.0.0-beta.5",
  "@rails/actioncable": "^6.0.0"
}
```

**Comment by ayrton** [comment] 2021-02-09 11:38
The same issue can be reproduced from a fresh clone of [hotwired/hotwire-rails-demo-chat](https://github.com/hotwired/hotwire-rails-demo-chat)

https://user-images.githubusercontent.com/440926/107358271-78aa4300-6ad3-11eb-8345-3da01cfe7e3d.mov

**Comment by EogJ** [comment] 2021-02-09 14:09
I think this is due to Turbo returning a cached version of the page (which has the flash present) and displaying that to the user whilst it fetches and renders the fresh version (without the flash present), hence the Flashing flashes. As such your Flashing flashes are expected behaviour.

To resolve this I can see 3 options:

1) Disable Caching completely.

2) Listen for the before-cache event to remove / hide the flash elements before the cache is generated.
A list of all the the events can be found here:
https://turbo.hotwire.dev/reference/events

3) Watch for the "data-turbo-preview" attribute which is added to <html> element of the page when turbo is displaying the cache and using css / js to hide / remove the flash elements.

**Comment by ayrton** [comment] 2021-02-09 16:16
I was more thinking of a controller concern that tells hotwire not to cache this, similar to [`turbo_exempts_page_from_cache`](https://github.com/hotwired/turbo-rails/blob/main/app/helpers/turbo/drive_helper.rb) but on controller level. 
Default rails already comes with a [concern](https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/etag_with_flash.rb) that adds an etagger if a flash is present. The browser already knows if it's stale or not, turbo just ideally infers this too.

The pros are that we will still have caching, and that no extra JS in user land is required

**Comment by mxlje** [comment] 2021-02-09 18:07
I would suggest doing 2. from the reply above and listen to the before cache event to „clean up“ the page before it is cached.

There are other situations where this can be applied to as well, such as closing dropdowns or other interactive elements.

**Comment by ayrton** [comment] 2021-02-10 08:23
Adding a `data-turbo-cache="false"` to these elements with the following code for now:

```html
<div data-turbo-cache="false">flash[:notice]</div>
```

```js
document.addEventListener("turbo:before-cache", () => {
   const flash = document.querySelector('[data-turbo-cache="false"]');

   if (flash) {
     flash.remove();
   }
 });
```

@dhh what are your thoughts on having something more built-in? Personally I think it'd be pretty sweet if the turbo cache would respect the already set cache headers / etags. But possibly this is too convoluted from a technical pov and I'd assume a 

```html
<div data-turbo-cache="false"></div>
```

would be the next best thing

**Comment by SleeplessByte** [comment] 2021-02-13 22:22
(This was also behaviour in Turbolinks. Manually removing flash items is something I've done for years to fix this).

**Comment by ayrton** [comment] 2021-02-22 10:04
> (This was also behaviour in Turbolinks. Manually removing flash items is something I've done for years to fix this).

Yep, I think it'd be pretty sweet to have this built in 🚀 Going to take a stab at opening a PR while awaiting a reply from a maintainer to see if this is a direction we are willing to take

**Comment by dhh** [comment] 2021-04-08 12:31
IMO it's best if we add data-turbo-cache="false" to individual dom elements that we don't wish included in the cache. I'd be happy to see that. Needs to happen in the hotwired/turbo repo. Feel free to propose/PR it there 👍

**Closed by dhh** 2021-04-08 12:31 UTC
