### ISSUE TITLE
After updated to 1.1.1, ActionText attachments are not showing

### ISSUE THREAD

**Issue by YutoYasunaga** [hotwired/turbo-rails#340] opened 2022-05-26 04:39 UTC
After updated turbo-rails to version 1.1.1. persisted ActionText attachments are not showing anymore, it looks like this:

![image](https://user-images.githubusercontent.com/6220668/170416938-4c1a0509-ff4b-4340-a3e4-c5d0eb4dde2e.png)

**When I restored to version 1.0.1, it works fine.**

**Comment by dhh** [comment] 2022-05-26 09:49
Can't replicate that on a new Rails app with turbo-rails 1.1.1 and Action Text. Need more detail. Look in the logs, look in the JavaScript console for errors.

**Comment by artisr** [comment] 2022-05-31 13:38
I also have the same issue 
This https://github.com/hotwired/turbo-rails/commit/102e919318ec528b9f5908e10d6427847d7a197b is to blame, at least in my case

**Comment by ccasabona** [comment] 2022-06-01 19:53
I have the same problem on an app with around 125 attachments.  

Here is a link to a demo app, as requested above.   The demo uses Rails 7.0.3, and turbo-rails with importmaps.  This was setup using ruby 3.1.2.

To demonstrate the problem, first use the app and attach an image using turbo-rails 1.0.1.  Then upgrade the v 1.1.1.  The image does does not display.   I get 404 errors in the console and in the rails log.

 If you attach the same image using turbo-rails 1.1.1, it displays properly.  This is impractical for apps with many attachments.

[https://github.com/ccasabona/noatt.git]( https://github.com/ccasabona/noatt.git)

**Comment by tleish** [comment] 2022-06-02 06:11
@ccasabona - I just tried the demo app on ruby 3.1.2.  It worked for me on turbo-rails 1.0.1 and then again on and turbo-rails 1.1.1.  I am unable to reproduce the issue.  I tested on MacOS using the latest Chrome and Firefox, worked on both.  Note: I do have "disable caching" in the browser enabled.  Is it possible there might be a cached javascript asset?

**Comment by ccasabona** [comment] 2022-06-02 11:51
Still the same problem with caching disabled on latest Safari, Firefox, and Chrome using MacOS.  I notice in the rails log that after upgrading to 1.1.1, the ActiveStorage::Blob Load statement is not present.

Here is my log under v 1.0.1:

```
Started GET "/contents/1" for ::1 at 2022-06-02 07:33:31 -0400
Processing by ContentsController#show as HTML
  Parameters: {"id"=>"1"}
  Content Load (0.1ms)  SELECT "contents".* FROM "contents" WHERE "contents"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]] app/controllers/contents_controller.rb:64:in `set_content'
  Rendering layout layouts/application.html.erb
  Rendering contents/show.html.erb within layouts/application
  ActionText::RichText Load (0.2ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_id" = ? AND "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? LIMIT ?  [["record_id", 1], ["record_type", "Content"], ["name", "body"], ["LIMIT", 1]]
  ↳ app/views/contents/_content.html.erb:4
  ActiveStorage::Blob Load (0.1ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 10], ["LIMIT", 1]]
  ↳ app/views/contents/_content.html.erb:4
  Rendered active_storage/blobs/_blob.html.erb (Duration: 12.8ms | Allocations: 3538)
  Rendered /Users/charlie/.rvm/gems/ruby-3.1.2/gems/actiontext-7.0.3/app/views/action_text/contents/_content.html.erb within layouts/action_text/contents/_content (Duration: 56.8ms | Allocations: 17401)
  Rendered contents/_content.html.erb (Duration: 79.0ms | Allocations: 28914)
  Rendered contents/show.html.erb within layouts/application (Duration: 87.1ms | Allocations: 34077)
  Rendered layout layouts/application.html.erb (Duration: 135.1ms | Allocations: 60412)
Completed 200 OK in 156ms (Views: 137.0ms | ActiveRecord: 2.1ms | Allocations: 70908)
```

After installing v  1.1.1:
```

Started GET "/contents/1" for ::1 at 2022-06-02 07:42:10 -0400
   (0.5ms)  SELECT sqlite_version(*)
  ActiveRecord::SchemaMigration Pluck (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by ContentsController#show as HTML
  Parameters: {"id"=>"1"}
  Content Load (0.1ms)  SELECT "contents".* FROM "contents" WHERE "contents"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/contents_controller.rb:64:in `set_content'
  Rendering layout layouts/application.html.erb
  Rendering contents/show.html.erb within layouts/application
  ActionText::RichText Load (0.2ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_id" = ? AND "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? LIMIT ?  [["record_id", 1], ["record_type", "Content"], ["name", "body"], ["LIMIT", 1]]
  ↳ app/views/contents/_content.html.erb:4
  Rendered /Users/charlie/.rvm/gems/ruby-3.1.2/gems/actiontext-7.0.3/app/views/action_text/attachables/_remote_image.html.erb (Duration: 0.9ms | Allocations: 371)
  Rendered /Users/charlie/.rvm/gems/ruby-3.1.2/gems/actiontext-7.0.3/app/views/action_text/contents/_content.html.erb within layouts/action_text/contents/_content (Duration: 19.5ms | Allocations: 6478)
  Rendered contents/_content.html.erb (Duration: 41.6ms | Allocations: 17991)
  Rendered contents/show.html.erb within layouts/application (Duration: 49.1ms | Allocations: 23208)
  Rendered layout layouts/application.html.erb (Duration: 98.9ms | Allocations: 49303)
Completed 200 OK in 118ms (Views: 101.1ms | ActiveRecord: 1.4ms | Allocations: 59799)


Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--126e48be514fba16e8b68e014d3491592ee17ec9/daisies-275.jpg" for ::1 at 2022-06-02 07:42:11 -0400
Processing by ActiveStorage::Blobs::RedirectController#show as JPEG
  Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--126e48be514fba16e8b68e014d3491592ee17ec9", "filename"=>"daisies-275"}
Filter chain halted as :set_blob rendered or redirected
Completed 404 Not Found in 92ms (ActiveRecord: 0.0ms | Allocations: 5379)


```

There is no `ActiveStorage::Blob Load ` request.  

I get the same problem if I reverse the conditions.  If I attach an image under v 1.1.1 and change turbo-rails to 1.0.1, the log result is the same.

**Comment by aaronjensen** [comment] 2022-06-02 15:43
This makes me think that this should have been a major version with an upgrade guide. It’s more than just invalidating sessions apparently.

**Comment by aaronjensen** [comment] 2022-06-02 15:44
Is there a way to migrate attachment hashes?

**Comment by tleish** [comment] 2022-06-02 22:14
I reproduced the issue.  Reverting https://github.com/hotwired/turbo-rails/pull/335 resolves it for me as well:

**Comment by aaronjensen** [comment] 2022-06-02 22:48
All #335 does is cause Rails to respect the hash algorithm default. If you are affected by this, set it to SHA1.

```
ActiveSupport::KeyGenerator.hash_digest_class = OpenSSL::Digest::SHA1
```

**Comment by dhh** [comment] 2022-06-03 06:19
Yeah the broken images are due to the fact that their keys were generated with a key generator that's not the same as the one using to decode it. So somehow this default change screwed with that.

**Comment by dhh** [comment] 2022-06-03 06:19
@tleish could you look at the different key generators that are set with and without that change? Somethjng clear got moved.

**Comment by dhh** [comment] 2022-06-03 06:20
No way to migrate hashes easily in already generated content. So can't have this change on people. Need to revert this or amend so there's no change for existing folks, then release.

**Comment by tleish** [comment] 2022-06-03 06:53
@dhh 

In Rails 7, the difference is based on a the caching of `@hash_digest_class` class variable inside `ActiveSupport::KeyGenerator`.  One path caches the variable to `SHA1`, the other path caches it to `SHA256`:

```ruby
module ActiveSupport
  # KeyGenerator is a simple wrapper around OpenSSL's implementation of PBKDF2.
  # It can be used to derive a number of keys for various purposes from a given secret.
  # This lets Rails applications have a single secure secret, but avoid reusing that
  # key in multiple incompatible contexts.
  class KeyGenerator
    class << self
      def hash_digest_class=(klass)
        if klass.kind_of?(Class) && klass < OpenSSL::Digest
          @hash_digest_class = klass
        else
          raise ArgumentError, "#{klass} is expected to be an OpenSSL::Digest subclass"
        end
      end

      def hash_digest_class
        @hash_digest_class ||= OpenSSL::Digest::SHA1
      end
    end
```

## BEFORE
Previous turbo-rails code executed `def hash_digest_class`.   `@hash_digest_class` was not yet set, and therefore defaulted to `SHA1`:
```ruby
    initializer "turbo.signed_stream_verifier_key" do
      Turbo.signed_stream_verifier_key = config.turbo.signed_stream_verifier_key ||
        Rails.application.key_generator.generate_key("turbo/signed_stream_verifier_key")
    end
```

## AFTER

Now, the code first sets the cached variable `@hash_digest_class` to SHA256 via `ActiveSupport::Railtie` first

```ruby
module ActiveSupport
  class Railtie < Rails::Railtie
   #...
    initializer "active_support.set_key_generator_hash_digest_class" do |app|
      config.after_initialize do
        if klass = app.config.active_support.key_generator_hash_digest_class # OpenSSL::Digest::SHA256
          ActiveSupport::KeyGenerator.hash_digest_class = klass
        end
      end
    end
```
after which the turbo-rails change uses the cached var:

```ruby
    initializer "turbo.signed_stream_verifier_key" do
      config.after_initialize do
        Turbo.signed_stream_verifier_key = config.turbo.signed_stream_verifier_key ||
          Rails.application.key_generator.generate_key("turbo/signed_stream_verifier_key")
      end
    end
```

The following does fix the issue, but doesn't seem to be the right fix.
`ActiveSupport::KeyGenerator.hash_digest_class = OpenSSL::Digest::SHA1` 
or 
`config.active_support.key_generator_hash_digest_class = OpenSSL::Digest::SHA1`

**Comment by aaronjensen** [comment] 2022-06-03 14:17
> No way to migrate hashes easily in already generated content. So can't have this change on people. Need to revert this or amend so there's no change for existing folks, then release.

@dhh I'm sorry I didn't make it clear what this change did, as I thought it was clear from the original issue in https://github.com/hotwired/turbo-rails/issues/325. I only talked about invalidating sessions because I didn't know that it would also break attachments somehow. As an aside, does this mean that secret key rotation is impossible/challenging?

As for this change, reverting it will revert to the buggy behavior:

When turbo-rails is installed, a Rails 7 app will go from SHA256 to SHA1 for its keys. In short, the same thing will happen that's happening to people now. But, since turbo-rails is often installed with Rails, it's likely to affect fewer people. It affected us because we used Rails without turbo in production and then added Turbo later.

If I may, I can suggest a couple alternatives, though I have no way of knowing how palatable any of them will be given so I won't recommend one.

A. Pull the current version of turbo-rails and release a new major version with documentation about what happened, what was fixed, and what you must do to explicitly opt back in to SHA1 if you are impacted.
B. Add a permanent-until-the-next-major-version check to the initializer I changed, which will detect the problematic condition and force the user to manually resolve it.

```rb
if ActiveSupport::KeyGenerator.hash_digest_class != app.config.active_support.key_generator_hash_digest_class
  raise "some explanatory error"
end
```

Thoughts? Any other ideas?

**Comment by tleish** [comment] 2022-06-07 06:42
Is this possibly a Ruby on Rails bug?  The fact that you can incorrectly override the default `ActiveSupport::KeyGenerator.hash_digest_class` by requesting it before it's used?

One other question on the fallback.  Would it be possible to use a try/catch on the read of the active storage blob?  If reading the blob fails AND `ActiveSupport::KeyGenerator.hash_digest_class != OpenSSL::Digest::SHA1`, then attempt to read the blob using a fallback of `OpenSSL::Digest::SHA1`?

This allows an upgrade while still reading old active storage blobs.

**Comment by aaronjensen** [comment] 2022-06-07 12:58
@tleish yes, I think this is a Rails bug/design flaw (see my original issue). 

It’s not just storage blobs though, it’s sessions and probably other things. I don’t know what the full scope is.

**Comment by dhh** [comment] 2022-06-18 13:53
Yeah, it is unfortunately not easy to migrate these existing Action Text embeds for key rotation. Seems to me that we're better off restoring the previous behavior, release a new minor version, then do a major version with the change, and that version detects the clash and asks you to resolve. Makes sense?

**Comment by aaronjensen** [comment] 2022-06-18 13:56
That sounds like a good plan to me. How can I help? 

Do you think we could get the minor and the major teed up to release at the same time or should we give it some time?

**Comment by atstockland** [comment] 2022-09-10 02:11
Where did this leave off?  I recently upgraded to Rails 7 defaults from 6.1, upgraded @rails/activestorage & @rails/actiontext & @rails/actioncable from 6.0.3-4 to 7.0.3-1.  After doing so---I found that all ActionText embeds were then broken links.

After following this conversation, I added "ActiveSupport::KeyGenerator.hash_digest_class = OpenSSL::Digest::SHA1" to an initializer---which did not resolve the issue.  I then downgraded the above items back to 6.0.3-4---which also did not resolve the issue.  My embeds are still broken.

I also followed GoRails #452 "How To Update ActionText Attachments"---which also did not resolve the broken embeds.

I anticipated downgrading to resolve the issue, but it did not.  Is there any further guidance or progress on this issue?  THANKS!

**Comment by atstockland** [comment] 2022-09-10 02:38
Downgrading the turbo-rails gem from 1.1.1 to 1.1.0 did resolve broken embeds.

**Comment by aaronjensen** [comment] 2022-09-10 03:06
@atstockland try putting that snippet in your application.rb either before or inside the configure block. An initializer would be too late most likely.

**Comment by atstockland** [comment] 2022-09-10 03:31
Thanks @aaronjensen that did it.  I reset the gem to 1.1.1, and move the snippet to application.rb and embeds are still loading ok.  :)

**Comment by brunoprietog** [comment] 2022-09-13 05:42
This change seems to affect not only action text, it also affects sessions, signed id, among others. Reverting the key generator to SHA1 will cause problems for those of us who are on SHA256 now. In my case, it would break some links with signed ids that I am mailing. Thanks

**Comment by jeremiemv** [comment] 2022-09-23 17:30
Was hoping that the `1.3.0` would unblock the situation. Doesn't look like it. So it seems that the current status quo for non greenfield applications is to lock version to`1.1.0` until a major release like `2.0`?

**Comment by aaronjensen** [comment] 2022-09-23 17:53
@jeremiemv Why would a greenfield application use the old version? 1.1.1 causes the actual configured hash algorithm to be used, rather than the less secure SHA1. The problem people are facing is that when they *update* an existing app that was previously not respecting their configuration, it starts to respect it, which effectively "breaks" attachments. The work around for them is to change your configuration to match what it was accidentally before.

The only risk to greenfield applications would be if the change in 1.1.1 was completely reverted, rather than doing what I proposed above. That seems like it would be a bad idea, because it'd break existing projects again that migrated (and  new projects that started with 1.1.1) without warning.

**Comment by marcelolx** [comment] 2022-09-23 18:01
@aaronjensen he did say "non greenfield"

**Comment by aaronjensen** [comment] 2022-09-23 18:03
@marcelolx ah, my mistake! GitHub had greenfield on its own line and I missed the non. Thanks.

**Comment by jeremiemv** [comment] 2022-09-23 20:15
Thanks @aaronjensen for being so reactive, and @marcelolx. I added an hyphen, _non-greenfield_, to avoid potential confusion with formatting. 

Going to look into configuring `hash_digest_class`. Need to make sure it won't have side effects on other hashed/encrypted features I am using.

**Comment by alsted** [comment] 2022-10-03 09:49
Im also struggling with this issue.  I'm unsure if i have some other permutation due to using google as storage. Other storage elements works with fine, as an example i have image upload using activestorage and those images are found and shown correctly. This makes me believe that that im still facing issues with actiontext.

My log:
`web_1  | 09:26:50 web.1  | I, [2022-10-03T09:26:50.327732 #42]  INFO -- : Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--191b31b811bc180613025eba42905f89d24952f4/IMG_20220924_141102.jpg" for 172.26.0.1 at 2022-10-03 09:26:50 +0000
web_1  | 09:26:50 web.1  | I, [2022-10-03T09:26:50.337321 #42]  INFO -- : Cannot render console from 172.26.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1  | 09:26:50 web.1  | I, [2022-10-03T09:26:50.471623 #42]  INFO -- : Processing by ActiveStorage::Blobs::RedirectController#show as JPEG
web_1  | 09:26:50 web.1  | I, [2022-10-03T09:26:50.472443 #42]  INFO -- :   Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--191b31b811bc180613025eba42905f89d24952f4", "filename"=>"IMG_20220924_141102"}
web_1  | 09:26:50 web.1  | I, [2022-10-03T09:26:50.473787 #42]  INFO -- : Filter chain halted as :set_blob rendered or redirected
web_1  | 09:26:50 web.1  | I, [2022-10-03T09:26:50.476272 #42]  INFO -- : Completed 404 Not Found in 3ms (ActiveRecord: 0.0ms | Allocations: 920)` 

From my gem file
`ruby '3.0.3'`
`gem 'turbo-rails', '~> 1.0', '>= 1.3.0'`
`gem 'actiontext', '~> 7.0', '>= 7.0.4'`
`gem 'rails', '~> 7.0.4'`

My application.rb has the following as per this issue:

  `class Application < Rails::Application`
`    config.load_defaults 7.0`
`    #JAH must stay on old SHA in order to ensure activetext working images see https://github.com/hotwired/turbo-rails/issues/340`
`    ActiveSupport::KeyGenerator.hash_digest_class = OpenSSL::Digest::SHA1`

Any other ideas on what to do to overcome this issue?

Thanks in advance

**Comment by alsted** [comment] 2022-10-03 12:22
I just needed to supply more in the application file:

```
    config.load_defaults 7.0
    #JAH must stay on old SHA in order to ensure activetext working images
    ActiveSupport::KeyGenerator.hash_digest_class = OpenSSL::Digest::SHA1
    config.active_support.key_generator_hash_digest_class = OpenSSL::Digest::SHA1
```

Works for me on my setup.

**Comment by philipithomas** [comment] 2022-10-31 23:42
This is a nasty issue for active text. I've ended up in a state where active text users have two different hash functions going on, and there doesn't seen to be a workaround for that. 

While this issue touches a lot of parts of Rails - I think it should also be a sign that Active Text could be made more robust, too.

**Comment by dhh** [comment] 2022-11-12 13:07
Yeah this is really annoying. What we need to do to fix this proper is to have a way to have multiple verifiers configured, so we can deal with multiple different signings. If anyone is interested in working on that, please do.

**Comment by pc0957** [comment] 2022-11-14 13:12
same issue here .. after uploading an image via trix editor, still image not displaying on web page.. please help me.

**Comment by 800a7b32** [comment] 2023-02-16 10:21
just come across this issue ourselves in the exact same way as @silva96 - not yet found a solution that works for us

**Comment by YutoYasunaga** [comment] 2023-02-20 07:39
@800a7b32 Yes. This is an issue and had no solution yet.

I still using version 1.0.1

**Comment by aaronjensen** [comment] 2023-02-20 13:45
This is a configuration setting. If you relied on the old one and later versions change it, set it to the old one manually. See my tips above. I can’t think of a reason someone wouldn’t be able to upgrade unless they are trying to do it without respecting the fact that the new version effectively changes the default.

**Comment by kevinmcconnell** [comment] 2023-02-21 15:46
You can also use a key rotation to ensure that your old asset links don't break when upgrading to a later turbo-rails version. I think this is the only option if you've ended up with assets using both the SHA1 and SHA256 based keys.

Putting the following in an initializer should solve it, by adding a SHA1-based key as the fallback to the new SHA256 one:

```ruby
Rails.application.config.after_initialize do |app|
  key_generator = ActiveSupport::KeyGenerator.new app.secret_key_base,
    iterations: 1000,
    hash_digest_class: OpenSSL::Digest::SHA1

  app.message_verifier("ActiveStorage").rotate(key_generator.generate_key("ActiveStorage"))
end
```

(Note that you need to do this in `after_initialize` to avoid triggering [the original bug](https://github.com/hotwired/turbo-rails/issues/325)!)

I'll add something to the turbo-rails docs about this, too.

**Comment by kevinmcconnell** [comment] 2023-02-23 12:25
We've added some information about this to [the docs](https://github.com/hotwired/turbo-rails/blob/main/UPGRADING.md#key-digest-changes-in-111). Hopefully those docs, and this issue, give everyone affected enough information to adjust their configuration to resolve the issue.

I think we can close this issue now since there's not any more action for us to take on it. @aaronjensen's fix in #335 remains the correct solution to the original problem, so Turbo Rails now behaves properly in that regard.

It's disappointing that fixing the bug leaves some people with assets stored using a different key than expected, for sure. But keeping the old behaviour would only be prolonging the problem. I don't think Turbo Rails should try to account for any data that might have been affected (e.g. by adding a key rotation automatically). Many applications using Turbo Rails won't have been affected by this issue, and it would be hard for us to know with certainty what resolution each app needs.

It might also be helpful to consult the [Rails upgrading docs about the digest class change](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#key-generator-digest-class-changing-to-use-sha256), as it addresses the same situation in another context.

**Closed by kevinmcconnell** 2023-02-23 12:25 UTC

**Comment by aaronjensen** [comment] 2023-02-23 12:37
That’s great, thank you @kevinmcconnell

**Comment by YutoYasunaga** [comment] 2023-02-25 01:54
@kevinmcconnell Thank you very much! It's worked for me

Just added this to /config/initializers
```ruby:config/initializers/active_storage.rb
Rails.application.config.after_initialize do |app|
  key_generator = ActiveSupport::KeyGenerator.new app.secret_key_base,
    iterations: 1000,
    hash_digest_class: OpenSSL::Digest::SHA1

  app.message_verifier("ActiveStorage").rotate(key_generator.generate_key("ActiveStorage"))
end
```

**Comment by saidmaadan** [comment] 2023-03-25 17:15
Add this line to config/application.rb 

config.active_storage.variant_processor = :mini_magick

**Comment by MattBudz** [comment] 2023-05-08 13:07
I have an app in production in a state where images were stored using SHA1 and SHA256.

Currently, only new (SHA256) images are rendered. If I use the solution suggested by @kevinmcconnell 
```ruby
Rails.application.config.after_initialize do |app|
  key_generator = ActiveSupport::KeyGenerator.new app.secret_key_base,
    iterations: 1000,
    hash_digest_class: OpenSSL::Digest::SHA1

  app.message_verifier("ActiveStorage").rotate(key_generator.generate_key("ActiveStorage"))
end
```
then only the old (SHA1) images are rendered. While the new (SHA256) images are broken. Unfortunately re-uploading images isn't possible. Is there a solution where the images will render regardless if they were stored with SHA1 or SHA256?

**Comment by ccasabona** [comment] 2023-05-08 13:33
This problem i s truly a Beldar Conehead “Mebbs,  I cannot think of everything!“ programming mishap.

So far, there is no solution to this vexing problem meaning that you simply can’t have it both ways.  I have an a production app with over 200 pdf images attached using SHA1.  Until such time as some underlying change in Rails or some other gem blocks rendering these images, this app is going to stay on SHA1.  I could go in and delete the attachments and upload them again under SHA256, but as long as they can render somehow, that isn’t going to happen.

It does give one the uneasy feeling that sometime in the future SHA1 projects will be forced to switch to SHA256 for some as yet unforeseen but equally complex reason.

**Comment by tomfast** [comment] 2024-01-11 22:32
> @atstockland try putting that snippet in your application.rb either before or inside the configure block. An initializer would be too late most likely.

This was the ticket for me @aaronjensen . Thanks for this! :partying_face: I ended up adding the following to my `config/application.rb` after upgrading from `1.0.1` to `1.5.0`:

```ruby
    config.after_initialize do |app|
      key_generator = ActiveSupport::KeyGenerator.new app.secret_key_base,
                                                      iterations: 1000,
                                                      hash_digest_class: OpenSSL::Digest::SHA1

      app.message_verifier('ActiveStorage').rotate(key_generator.generate_key('ActiveStorage'))
    end
```

Adding the above to an initializer didn't work for me, probably related to something in the overall app initialization process (local issue).

**Comment by bekkii77** [comment] 2024-01-17 23:39
Is there a way to migrate my existing SHA1 active storage blobs over to SHA256 so that I can move my app to SHA256 altogether?  I'm in the same situation as Matt B where now (because we didn't notice this issue for a month) I have some images in each hash digest.  The config change added to the documentation (thanks @kevinmcconnell) does help us get our old images rendering, but leaves our new ones broken.  

And there's another side effect we've come across - if I edit the record that references the old image (like in a trix editor), the old image will no longer render, presumably because when the save occurs, it uses SHA256.

**Comment by MattBudz** [comment] 2024-01-18 12:55
@bekkii77 have you tried what @aaronjensen [suggested](https://github.com/hotwired/turbo-rails/issues/340#issuecomment-1242604255)? Putting the snippet in the `application.rb` either before or inside the configure block? 

I have to go back to this project and give this a whirl myself, but it sounds like it's the solution here.

**Comment by lakim** [comment] 2024-05-02 07:35
None of the above worked for me, but I managed to migrate all ActionText attachments thanks to [GoRails - How To Update ActionText Attachments](https://gorails.com/episodes/how-to-update-actiontext-attachments).
You don't even need a GoRails subscription, just look at the [Rake task](https://github.com/gorails-screencasts/452-action-text-upgrade/blob/master/lib/tasks/action_text.rake) in the code for the episode.

I find that it's an even cleaner solution. Only new digests are in the DB, and no rotation needed.

**Comment by ccasabona** [comment] 2024-05-03 14:29
The [Rake Task](https://github.com/gorails-screencasts/452-action-text-upgrade/blob/master/lib/tasks/action_text.rake) works!.  I was able to successfully migrate all the ActionText attachments made under turbo-rails prior to v1.1.1.

I then removed the `config.active_support.key_generator_hash_digest_class = OpenSSL::Digest::SHA1` from config.application.rb

When the task runs under mysql, this warning is generated:

`WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.`

This doesn't prevent the rake task from converting the attachment digests (apparently) correctly, but I'm not sure what that means once the deprecation takes place.

Cheers

**Comment by brendon** [comment] 2025-02-12 22:48
> > [@atstockland](https://github.com/atstockland) try putting that snippet in your application.rb either before or inside the configure block. An initializer would be too late most likely.
> 
> This was the ticket for me [@aaronjensen](https://github.com/aaronjensen) . Thanks for this! 🥳 I ended up adding the following to my `config/application.rb` after upgrading from `1.0.1` to `1.5.0`:
> 
>     config.after_initialize do |app|
>       key_generator = ActiveSupport::KeyGenerator.new app.secret_key_base,
>                                                       iterations: 1000,
>                                                       hash_digest_class: OpenSSL::Digest::SHA1
> 
>       app.message_verifier('ActiveStorage').rotate(key_generator.generate_key('ActiveStorage'))
>     end
> Adding the above to an initializer didn't work for me, probably related to something in the overall app initialization process (local issue).

Agreed. I'm upgrading from 6.2 to eventually 8.0. The initialiser worked for Rails 7.0 but not for 7.1. It's be interesting to know why that is but this works for now. Perhaps there's another hook we can use that runs earlier than `after_initialize`?
