### ISSUE TITLE
Can't load turbo-rails without Action Cable starting in Rails 7.1.2

### ISSUE THREAD

**Issue by mattbrictson** [hotwired/turbo-rails#512] opened 2023-11-10 22:24 UTC
I'm not sure whether to report this bug here, or in Rails. Let me know if I should move it.

With today's release of Rails 7.1.2, it is no longer possible to use turbo-rails without Action Cable. I get the following error when eager loading is enabled:

```
NameError: uninitialized constant ActionCable (NameError)

class Turbo::StreamsChannel < ActionCable::Channel::Base
                                                  ^^^^^^
Did you mean?  Rational
/Users/mbrictson/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/turbo-rails-1.5.0/app/channels/turbo/streams_channel.rb:34:in `<main>'
```

This check in the turbo-rails engine is supposed to automatically remove `app/channels` from the eager-load paths when Action Cable is not present:

https://github.com/hotwired/turbo-rails/blob/e44b6a98a77a0a2cc927f986a67517d73c4c9246/lib/turbo/engine.rb#L18-L20

However, starting with Rails 7.1.2, this technique apparently no longer works.

There were changes in Rails 7.1.2 regarding auto/eager loading of paths in engines (see https://github.com/rails/rails/pull/49636), so this could be a new bug Rails, or it could mean that turbo-rails needs to be changed to accommodate the new behavior.

_Edit: I confirmed that rolling back https://github.com/rails/rails/pull/49636 fixes the problem._

**Comment by dhh** [comment] 2023-11-10 22:35
cc @fxn

**Comment by fxn** [comment] 2023-11-10 23:49
ACK. This gem supports Rails 6.0, need to think about a patch that works for both autoloaders.

The root problem here is an inconsistency between the `config.*` endpoints for paths that has been there since Rails 3. That `delete` call worked by pure chance, it wouldn't have worked for `config.autoload_paths` because that API is not really designed to support this.

In case it helps urgently, in Rails 7.1 you can throw this in an application initializer:

```ruby
Rails.autoloaders.once.do_not_eager_load("#{Turbo::Engine.root}/app/channels")
```

off the top of my head.

It's near 1 AM over here.

**Comment by mattbrictson** [comment] 2023-11-11 00:00
Not urgent! Let me know if there is anything I can do to help.

For now, I am working around the issue by loading Action Cable:

```
# config/application.rb

require "action_cable/engine"
```

**Comment by zarqman** [comment] 2023-11-11 18:22
Based on #513, here's a workaround if you don't want to load ActionCable.
```ruby
# config/application.rb

module YourApp
  class Application < Rails::Application
    ...
    Rails.autoloaders.once.do_not_eager_load("#{Gem.loaded_specs['turbo-rails'].full_gem_path}/app/channels")
  end
end
```

**Comment by fxn** [comment] 2023-11-11 18:28
@zarqman actually, shared a one-liner above that is a bit simpler.

**Comment by zarqman** [comment] 2023-11-11 18:43
@fxn, ack, missed that! Thanks!

**Comment by xymbol** [comment] 2023-11-13 01:51
@fxn I ran into this issue, too, and I confirm that your workaround above works. Thank you!

**Comment by mattbrictson** [comment] 2023-11-13 15:10
> I had this on the CI but not in the local environment

@xymbol this is because, by default, Rails enables eager loading in CI test environments, but not local test environments. See `config/environments/test.rb`:

```ruby
config.eager_load = ENV["CI"].present?
```

https://github.com/rails/rails/blob/v7.1.2/railties/lib/rails/generators/rails/app/templates/config/environments/test.rb.tt#L14-L18

**Comment by xymbol** [comment] 2023-11-13 15:43
@mattbrictson TIL, thank you.

**Comment by dorianmariecom** [comment] 2024-03-06 12:21
What's the status of this? Do we still need the workaround?

**Comment by fxn** [comment] 2024-03-06 12:27
@dorianmariecom totally forgot about this ticket, I'll write back!

**Comment by dorianmariecom** [comment] 2024-03-06 14:12
```
/home/runner/work/haymakers-for-hope-web/haymakers-for-hope-web/vendor/bundle/ruby/3.3.0/gems/turbo-rails-2.0.4/app/channels/turbo/streams_channel.rb:34:in `<main>': uninitialized constant ActionCable (NameError)

class Turbo::StreamsChannel < ActionCable::Channel::Base
                              ^^^^^^^^^^^
Did you mean?  ActionMailer
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /home/runner/work/haymakers-for-hope-web/haymakers-for-hope-web/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/work/haymakers-for-hope-web/haymakers-for-hope-web/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'
```

The issue is still there in my CI probably because of `config.eager_load = ENV["CI"].present?`

**Comment by fxn** [comment] 2024-03-10 19:22
@dorianmariecom The issue happens when eager loading is enabled, Action Cable is not loaded, and Rails is 7.1.2 or above.

I wrote a fix for this in November (#513), but in late January the PR was closed accidentally. I did a cleanup of repos and did not realize that was still not merged (I do not have commit bit in Hotwire).

I have created another PR with the fix (#601).

**Comment by dorianmariecom** [comment] 2024-03-10 20:22
@fxn thx you rock, and yeah I was wondering why the previous pull request was closed

**Closed** 2024-03-11 01:38 UTC

**Comment by dorianmariecom** [comment] 2024-03-11 09:15
Thanks @dhh <3

**Comment by EGiataganas** [comment] 2024-03-14 23:29
@fxn Thanks a lot for the fix, I've just has the same error and realised that is because there is not any new release so I've created a PR. Hope this helps 🙏
