### ISSUE TITLE
disabling turbo and delete method not working together (devise)

### ISSUE THREAD

**Issue by chmich** [hotwired/turbo-rails#388] opened 2022-09-29 21:16 UTC
**Hi**

`method: :delete` on a `link_to`:
rails-ujs is conflicting with turbo.
and switch-off turbo together with turbo-method is conflicting

That would be necessary for the sign-out route of Devise

rails 7.0.4

## Turbo disabled conflicting with delete-method

```
= link_to 'Destroy', article, data: { turbo: false, turbo_method: :delete }
# => <a data-turbo="false" data-turbo-method="delete" href="/articles/13">Destroy</a>
```
**=>** Turbo is off but its making now a get-request

## UJS cannot help when turbo is off

```
link_to 'Destroy', article, method: :delete, data: { turbo: false }
```
`application.js`
```
import Rails from '@rails/ujs';
Rails.start()

import * as Turbo from '@hotwired/turbo'
Turbo.start()
```

**=>** `method: :delete` is working (see it on Rails Console)
**=>** `data-turbo="false"` is NOT working and Turbo is running (see it on Browser/Developer-Tools/Konsole)

`application.js`
```
// import Rails from '@rails/ujs';
// Rails.start()

import * as Turbo from '@hotwired/turbo'
Turbo.start()
```
**=>** Now Turbo is off (like ist should), but, logically, `method: :delete` is also not working (link makes a GET request because missing ujs)

## Expected

ist should be possible to turn turbo off for a specific link like [described](https://turbo.hotwired.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms) but in that way that `data-turbo-method` works further on.

Conflicts between UJS and Turbo should be noticed on [GitHub/ujs](https://github.com/rails/rails-ujs) and [Hotwired/building your application](https://turbo.hotwired.dev/handbook/building)

**Thanks, 
Christian**

---

## Workaround

For those who are seeing this issue and needing a **workaround**:
use `button_to` instead of link_to. That creates a form with `delete` method and that works together with `devise`

```
= button_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo: :false }
```
with or without `data: {turbo: :false}`? both worked for me this case, when turbo and ujs are on

**Comment by marcoroth** [comment] 2022-09-29 23:13
Hey @chmich, thanks for opening this issue!

Turbo and Rails UJS are not meant to be used together like this.

Either you should use Turbo using `data-turbo-method` or just use `method="delete"` using UJS, but not combined - otherwise you'll run into weird issues as you discovered.

The `button_to` works regardless, because that helper outputs a full-blown `<form>` tag to your HTML, where your link/button is the submit button of that form.

I think in your case you should be good to go with just:

```html+erb
<%= link_to 'Destroy', article, data: { turbo_method: :delete } %>
```

I hope this helps!

**Comment by chmich** [comment] 2022-09-30 07:26
Thanks @marcoroth for clearifying!

Based on your feedback i modified the issue so that ist clearer what it should be.

And Yes, that Turbo and UJS not meant working together i thought but found it nowhere in the docs.
Where is that written?

But, on my case, turbo with devise, by `<%= link_to 'Destroy', article, data: { turbo_method: :delete } %>` is not working. Devise is logging out but then i get the error `No route matches [DELETE] "/"`, at least on my routes that are:

```
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new'
    end
    authenticated :user do

      root 'welcome#index', as: :authenticated_root
      .... here the other routes
```

Yes, [Alexandre in Hotrails/turbo-stream-security](https://www.hotrails.dev/turbo-rails/turbo-streams-security) seems to solve it. I followed his great tutorial but haven't done that page yet. From my view, it should be possible switching off turbo but in that way that `method: :delete` works further on. For me, for now, `button_to` is the safer workaround.

UJS/Turbo: I have UJS used in many of my rails app and i would not like having to change all my code. Question for me is: Can they really not living alongside?
For now i updated my [Tutorial](https://dev.to/chmich/rails-ujs-on-vite-b6m).

Many thanks!
Christian

**Comment by WriterZephos** [comment] 2023-08-26 00:49
I just ran into this issue. data-turbo-method doesn't seem to work when data-turbo=false.

**Comment by brunoprietog** [comment] 2024-06-21 12:36
Hello, `data-turbo-method` will not work if `data-turbo` is `false`. Closing because this is the expected behavior.

**Closed by brunoprietog** 2024-06-21 12:36 UTC
