### ISSUE TITLE
Module parse failed: Unexpected token (2:9)

### ISSUE THREAD

**Issue by stebo** [hotwired/turbo-rails#20] opened 2020-12-23 22:19 UTC
When adding turbo-rails to my already existing Rails 6 application (via **webpacker**, following the steps of the Readme), I get the following JS errors in the console:

```
Uncaught Error: Module parse failed: Unexpected token (2:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import "./cable_stream_source_element";
> export * as Turbo from "@hotwired/turbo";
| export * as cable from "./cable";
    at Object../node_modules/@hotwired/turbo-rails/app/javascript/turbo/index.js (application.js:2)
    at __webpack_require__ (bootstrap:19)
    at Module../app/webpacker/packs/application.js (application.js:1)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

I am quite helpless on what to do with those errors and if they are specific to my application or some general problem within the turbo package.

**Comment by nfilzi** [comment] 2020-12-24 02:10
Got the exact same error, haven't found anything relevant so far

**Comment by nfilzi** [comment] 2020-12-24 02:35
Found sth in the end 🎉 
According to [this SO answer](https://stackoverflow.com/a/33930998/4789597), apparently you can't export directly all exposed properties from another module. You need to import them first, then export them again.

Excuse me for any potential lack of clarity with my explanations, my JS bundling knowledge is ultra flaky 😁 

In the end, changing `turborails/javascript/turbo/index.js` from this:

```js
import "./cable_stream_source_element"
export * as Turbo from "@hotwired/turbo"
export * as cable from "./cable"

```

To this
```js
import "./cable_stream_source_element"

import * as Turbo from "@hotwired/turbo"
export { Turbo }

import * as cable from "./cable"
export { cable }
```

Did the trick for me locally 🎉 
<img width="1552" alt="Screenshot 2020-12-24 at 03 34 51" src="https://user-images.githubusercontent.com/7533706/103052262-fc968300-4598-11eb-8aed-ddc3da2f6ea8.png">

**Comment by nfilzi** [comment] 2020-12-24 02:46
@javan Anything we may have overlooked?

My findings fix the issue, but I'm wondering if it could be linked in the first place to sth peculiar in our dev setup locally? (node or webpack version, missing sth / sth extra in our webpack / babel config)?

**Comment by udkl** [comment] 2020-12-24 03:01
For context, this is a webpack 4 issue that's supposedly resolved in v5 : 
https://github.com/webpack/webpack/issues/10460
https://github.com/abpframework/abp/issues/6283

**Comment by javan** [comment] 2020-12-24 03:04
@nfilzi, your *To this* version looks good to me. Want to open a PR?

**Comment by nfilzi** [comment] 2020-12-24 11:59
Will do @javan :)

**Comment by javan** [comment] 2020-12-24 16:24
Closed via https://github.com/hotwired/turbo-rails/pull/26

**Closed by javan** 2020-12-24 16:24 UTC

**Comment by udkl** [comment] 2020-12-24 22:14
One way of getting the fix is to update `"@hotwired/turbo-rails": "hotwired/turbo-rails#47c7b545"` in your package.json

**Comment by ryw** [comment] 2020-12-26 14:04
> A temporary way of getting this fix is to update `"@hotwired/turbo-rails": "hotwired/turbo-rails#47c7b545"` in your package.json

Attempted this, now I get another js error `TypeError: Attempting to change the getter of an unconfigurable property.`

```
  Object.defineProperty(Event.prototype, "submitter", {
```

**Comment by ryw** [comment] 2020-12-26 14:14
Hmm tried to upgrade webpacker to 5.2.1, get same error, so maybe a different issue

**Comment by arpansac** [comment] 2020-12-27 04:01
Earlier installed and then removed stimulus_reflex.
Spent hours figuring out why my link_to inside a turbo frame was taking me to a different page. Finally, had to remove the javascript_pack_tag
Already have webpack 5.2.1
It doesn't display any error though, but the link_to inside turbo frame always tends to open the link in a new page instead of doing it inside the frame

**Comment by christos** [comment] 2021-01-14 08:48
> Attempted this, now I get another js error TypeError: Attempting to change the getter of an unconfigurable property. on Line 35 of turbo.source.js:

@ryw Although I have yet to manage to load `Turbo` successfully in the console, I did manage to get rid of that error. It was caused by having both `<%= stimulus_include_tags %>` and `<%= turbo_include_tags %>` in `application.html.erb`. I think it was basically trying to load an already loaded module and hence the error.

**Comment by goulvench** [comment] 2024-03-11 15:07
In my case this error was fixed by replacing `<%= javascript_packs_with_chunks_tag %>` with `<%= javascript_pack_tag %>`. Getting rid of Webpack is next on the list :-)
